### ISSUE TITLE
supporting markdown format

### ISSUE THREAD

**Issue by sillylogger** [tj/terminal-table#106]
Great tool, thanks so much for making it, I use it all the time.
I was pasting the result of a terminal table in a github README.md, and it occurred to me that terminal-table's output is very close to the [markdown format for tables](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables).  There only needs to be a slight modification of tables like:
```
+-----------------+-------+-------+
| Language Counts | total | %     |
+-----------------+-------+-------+
| en              | 1573  | 100.0 |
+-----------------+-------+-------+
```
to:
```
| Language Counts | total | %     |
|-----------------|-------|-------|
| en              | 1573  | 100.0 |
````
and then it would support output like:

| Language Counts | total | %     |
|-----------------|-------|-------|
| en              | 1573  | 100.0 |

Potentially a `markdown: true` option or even a switching of the default for the column separator.. Would you be open to a PR?  If so how flexible are you on:
- changing the default output to be consistent with markdown or an option param?
- changing the column separator to be consistent with markdown
- allowing annotations for the alignment in accordance with markdown
Cheers!

**Comment by toaco** [comment]
I use [markdown-tables](https://github.com/christopher-dG/markdown-tables) as an alternative,  I’m really hope that terminal-table can also support this feature

**Comment by sillylogger** [comment]
@toaco silly me, you can make this happen with a combination of styles: 
```
Terminal::Table::Style.defaults = {
  :border_top     => false,
  :border_bottom  => false,
  :border_x       => "-",
  :border_y       => "|",
  :border_i       => "|"
}
```

Yay, thanks @nateberkopec for making `terminal-table` so configurable!

**Comment by TylerRick** [comment]
Or if you just want to format it that way one-off for the current table you're working with without globally changing the defaults:
```ruby
markdown_style = {
  border_top:    false,
  border_bottom: false,
  border_x:      "-",
  border_y:      "|",
  border_i:      "|"
}
puts Terminal::Table.new(headings: ['heading A', 'heading B'], rows: [['a', 'b'], ['a', 'b']], style: markdown_style)
| heading A | heading B |
|-----------|-----------|
| a         | b         |
| a         | b         |
```

Some syntactic sugar would be nice, though, like:
```ruby
Terminal::Table.new(...).as_markdown
```
that would automatically add `style: markdown_style` without us end-users having to copy and paste that `markdown_style` hash wherever we want to output in that style.
