### ISSUE TITLE
Helper function to style as Markdown table

### ISSUE THREAD

**Issue by TylerRick** [tj/terminal-table#111]
For those of us who are already using this gem and don't want to install yet another dependency like [`markdown-tables`](https://github.com/christopher-dG/markdown-tables) just to get a more concise API for generating Markdown tables.

Thanks to this library's configurability, you _can_ already format your tables as Markdown format:
```ruby
markdown_style = {
  border_top:    false,
  border_bottom: false,
  border_x:      "-",
  border_y:      "|",
  border_i:      "|"
}
puts Terminal::Table.new(headings: ['heading A', 'heading B'], rows: [['a', 'b'], ['a', 'b']], style: markdown_style)
| heading A | heading B |
|-----------|-----------|
| a         | b         |
| a         | b         |
```

But it would be nice if we end-users didn't have to copy and paste that big `markdown_style` hash every place we wanted to output a table in Markdown format.

How about something like:
```ruby
Terminal::Table.new(...).as_markdown
```
that would automatically add `style: markdown_style` for you?

(In the future, we might consider making it do other things, too, like optionally escaping cell content if it contained any text that might be accidentally interpreted as Markdown format.)

(See also #106)

**Comment by nanobowers** [comment]
@nateberkopec  I think this can be closed -   fixed as part of #113
