### ISSUE TITLE
Please build terminal-table against unicode-display_width >= 2.0

### ISSUE THREAD

**Issue by dbro86** [tj/terminal-table#115]
Please build terminal-table against unicode-display_width >= 2.0

Kind regards
Brody

**Comment by mvz** [comment]
Isn't this already implemented in 5e4305fdb0a5b847f8805df86e2df2d3b0d63050?

**Comment by brodowskid** [comment]
Is it correct, that you close this feature request, but it is not released?

**Comment by dbro86** [comment]
Is this intentional, that even though the feature request is not yet released, it is closed?

**Comment by mvz** [comment]
That's how it usually goes, yes.

**Comment by nateberkopec** [comment]
I'll do a release sometime this week
