### ISSUE TITLE
Last row on empty tables only has separator between first and second columns

### ISSUE THREAD

**Issue by mfoo** [tj/terminal-table#118]
Hello! After upgrading from 2.0.0 to 3.0.0 we've had a test fail because the last row of an empty table changed format.

Reproduction:

`Gemfile`:

```
source 'https://rubygems.org'
gem 'terminal-table', '~> 3.0.0'
```
Issue:
```
% bundle exec irb
irb(main):001:0> require 'terminal-table'
=> true
irb(main):002:0> a = Terminal::Table.new(headings: ['a', 'b', 'c'])
<snip output>
irb(main):003:0> puts a
+---+---+---+
| a | b | c |
+---+---+---+
+---+-------+
=> nil
irb(main):004:0>
```

The last line is now 

```
+---+-------+
```

but if you downgrade to `2.0.0` it is

```
+---+---+---+
```

Is this a bug?

**Comment by nanobowers** [comment]
Hi @mfoo 

At the very least it's undefined behavior that has changed between releases.  From what I can tell we have no testcases that have  a heading but no rows. 

In any event, I think this can be considered a bug - and I  think I found the culprit, which has to do with kwargs (or lack of).  The original code was presumably developed on older rubies that didnt support kwargs, and thus did a lot of option hash passing, which came back to bite us here.

Anyway, one interesting part of the behavior is that the header separator row is always inserted after the heading, even if there are no rows, thus you get both the separator under the heading and then another bottom-edge separator  (for unicode):
```
┌───┬───┬───┬───┐
│ a │ b │ c │ d │
╞═══╪═══╧═══╧═══╡
└───┴───────────┘
```
I think we probably shouldn't change that behavior though, seems like you relied on it.

Using this example code and and the updated fix:
```ruby
puts Terminal::Table.new(headings: ['a', 'b', 'c', 'd'], style: { border: :unicode })

puts

tbl = Terminal::Table.new do |t|
  t.style = { border: :unicode }
  t.add_separator
  t.add_separator
  t.add_row ['x','y','z']
  t.add_separator
  t.add_separator
end
puts tbl

puts

puts Terminal::Table.new(headings: [['a', 'b', 'c', 'd'], ['cat','dog','frog','mouse']], style: { border: :unicode })

puts

puts Terminal::Table.new(headings: ['a', 'b', 'c', 'd'])

puts

tbl = Terminal::Table.new do |t|
  t.add_separator
  t.add_separator
  t.add_row ['x','y','z']
  t.add_separator
  t.add_separator
end
puts tbl
```
Output:
```
┌───┬───┬───┬───┐
│ a │ b │ c │ d │
╞═══╧═══╧═══╧═══╡
└───────────────┘

┌───────────┐
├───────────┤
├───┬───┬───┤
│ x │ y │ z │
├───┴───┴───┤
├───────────┤
└───────────┘

┌─────┬─────┬──────┬───────┐
│ a   │ b   │ c    │ d     │
╞═════╪═════╪══════╪═══════╡
│ cat │ dog │ frog │ mouse │
╞═════╧═════╧══════╧═══════╡
└──────────────────────────┘

+---+---+---+---+
| a | b | c | d |
+---+---+---+---+
+---------------+

+-----------+
+-----------+
+---+---+---+
| x | y | z |
+---+---+---+
+-----------+
+-----------+

```

Will file a PR shortly with the fix.

**Comment by mfoo** [comment]
Thanks for the quick reply! There's no rush - we don't rely on the behaviour so there's no worries about changing it from us. Our test was testing the `stdout` of a tool that printed some data in a situation where the user's query returned no rows, so I've modified the test to ignore the last line. We don't rely on the behaviour (it should almost never return 0 rows, but even if it does, odd separators isn't an issue), and there's no reason for our test to essentially be testing rendering logic from this gem.

**Comment by mfoo** [comment]
Ah - I believe I misunderstood. I think visually I'd like to see the header separator in an empty table if there are no rows - I think my brain recognises

```
+---+---+---+
| a | b | c |
+---+---+---+
+---+---+---+
```
as an empty table but
```
+---+---+---+
| a | b | c |
+---+---+---+
```
as three boxes

**Comment by nateberkopec** [comment]
Fixed on master
