### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by christophermaier** [tj/terminal-table#27]
It's been over a year since the last release was pushed out to Rubygems, and a lot of code has gone into terminal-table since then.  

Any chance of pushing a new release?  Thanks!

**Comment by nateberkopec** [comment]
@tj Can you add me as an owner to rubygems?

**Comment by tj** [comment]
gah.. gem is craping out on me and won't authenticate, I'll check it out after work

**Comment by fluke777** [comment]
@nateberkopec @tj 
+1 Any update on this? It would be awesome to have a new release.

**Comment by nateberkopec** [comment]
As a stopgap, you can always do the following:

```ruby
gem 'terminal-table', github: 'tj/terminal-table', ref: '8c1910c'
```

**Comment by nateberkopec** [comment]
BOOM! 1.5.0 is released! Thanks for the add @tj!

![screen shot 2015-06-26 at 10 57 15 pm](https://cloud.githubusercontent.com/assets/845662/8390208/822dd8aa-1c56-11e5-9bd1-befddbf99e75.png)

**Comment by nateberkopec** [comment]
(I have no idea why the data on there is so wrong, oh well!)
