### ISSUE TITLE
UTF-8 characters containing lines produces wrong column width

### ISSUE THREAD

**Issue by blacktea** [tj/terminal-table#28]
UTF-8 characters containing lines produces wrong column width

At least working in rails 2.3 (ruby 1.8.7), mb_string.size and to_s.size differs, thus producing different column widths.

**Comment by sodabrew** [comment]
I am certain this can be closed. Ruby 1.9 and above correctly handles UTF-8 lengths by separating the character size from the byte size - see String#size and String#bytesize:

http://ruby-doc.org/core-1.9.3/String.html#method-i-size
http://ruby-doc.org/core-1.9.3/String.html#method-i-bytesize
