### ISSUE TITLE
WARNING: terminal-table-1.4.5 has an invalid nil value for @cert_chain

### ISSUE THREAD

**Issue by bcavileer** [tj/terminal-table#29]
When bundle install

WARNING: terminal-table-1.4.5 has an invalid nil value for @cert_chain

Google pointed me to http://docs.rubygems.org/read/chapter/21#page88

**Comment by nateberkopec** [comment]
Now that I'm a gem owner, we'll see what we can do here.

**Comment by nateberkopec** [comment]
I believe this should be resolved with 1.5.1.
