### ISSUE TITLE
chinese support

### ISSUE THREAD

**Issue by xuxiangyang** [tj/terminal-table#41]
When I use it to show Chinese table ,the cell alignment become not so beautiful。
![image](https://cloud.githubusercontent.com/assets/4926529/2992553/d6f72858-dc94-11e3-8a24-4c8a8d7e6dc9.png)

**Comment by nateberkopec** [comment]
Good idea! Not sure how complicated full UTF-8 support would be. I've never worked with Chinese characters before!

**Comment by nateberkopec** [comment]
Closing as dupe of #28 - let's continue the discussion there.
