### ISSUE TITLE
Version 1.4.5 source code / Wrong version in terminal-table.gemspec

### ISSUE THREAD

**Issue by korczis** [tj/terminal-table#53]
It seems that at the [rubygems](https://rubygems.org/gems/terminal-table) are release following versions.

1.4.5 - March 15, 2012 (14 KB)
1.4.4 - November 7, 2011 (14 KB)

Unfortunately in [terminal-table.gemspec](https://github.com/tj/terminal-table/blob/master/terminal-table.gemspec#L5) is version 1.4.3 specified.

What went wrong? Why there is older version? Where are the sources of version 1.4.5 ?

**Comment by nateberkopec** [comment]
@korczis Whoops! I have no idea. I guess "master" is currently on a sort of "1.5", I'll change that to at least fix master.

If you _really_ need the source of a previous terminal-table gem, investigate using `bundle open`.
