### ISSUE TITLE
LoadError: cannot load such file -- terminal-table/row in 1.5.0

### ISSUE THREAD

**Issue by erwanlr** [tj/terminal-table#55]
I had a report about this error here https://github.com/wpscanteam/wpscan/issues/839

After investigation, it's caused only in the latest 1.5.0 version release yesterday.

It was working fine in the 1.4.5

**Comment by jasnow** [comment]
I am having this problem too.

**Comment by Edderic** [comment]
Same. My tests for my project used to pass. It is now failing without adding any changes to it.

**Comment by nateberkopec** [comment]
Yeah, our gemspec is pretty ancient. I'll push out a hotfix release today.

**Comment by nateberkopec** [comment]
@erwanlr @jasnow @Edderic can you try pointing your respective gem files to:

```ruby
gem 'terminal-table', github: 'tj/terminal-table', branch: 'modernize'
```

and let me know if that works? If it does, I'll push a 1.5.1 release.

**Comment by jcmorrow** [comment]
I'm experiencing the same problem and no, that fix isn't working for me.

**Comment by erwanlr** [comment]
Fix is working, you have to ```bundle install/update``` (or re-install the gem from the fixed branch)

**Comment by nateberkopec** [comment]
Thanks for your patience, all. 1.5.1 has been pushed with a fixed gemspec.

**Comment by icco** [comment]
Post this update, I needed to change my Gemfile:

```diff
-gem "terminal-table", :require => "terminal-table/import"
+gem "terminal-table"
```

**Comment by nateberkopec** [comment]
Thanks, I had no idea people were doing that. Discussion/issue is at: #58
