### ISSUE TITLE
Gemspec does not include the spec directory

### ISSUE THREAD

**Issue by mrueg** [tj/terminal-table#60]
The tag is missing and the gem does not include the tests. :) Thanks!

**Comment by nateberkopec** [comment]
Oops, my bad! Fixed by adding a tag.

What do you mean by not including the tests?

**Comment by mrueg** [comment]
Thanks! The gem does not include the spec directory and its files.

**Comment by nateberkopec** [comment]
Fixed in b8c58ee85b54bdfce3
