### ISSUE TITLE
Can we use this to create 2d tables?

### ISSUE THREAD

**Issue by ambikashri** [tj/terminal-table#61]
I want to create a 2d table in the below format
Vitamin | Apple | Mango | Banana
A|
B|
C|
Where the above mentioned fields are the rows and columns and i need to fill data into this table.

**Comment by nateberkopec** [comment]
rows = []
rows << ['Vitamin', 'Apple', 'Mango', 'Banana']
rows << ['A', 2, 3, 4 ,5]
table = Terminal::Table.new :rows => rows
