### ISSUE TITLE
How to align headings?

### ISSUE THREAD

**Issue by casper** [tj/terminal-table#67]
Table data rows have `align_column`, which works great, but how do I align the heading of a table? 
I usually want to right-align numbers, but the heading would look better if it's also aligned the same.

**Comment by damonmcminn** [comment]
The [alignment](https://github.com/tj/terminal-table#alignment) section in the README also specifies the ability to align a cell. You can specify alignment when adding the headers array to the table, either through [constructor or setter](https://github.com/tj/terminal-table#constructor-options-and-setter-methods), however you will still need to use `table.align_column` for the table values.

e.g.
```ruby
table.headers = ['heading1', { value: 'heading2', alignment: :right }]
```
