### ISSUE TITLE
Consider tagging a new release

### ISSUE THREAD

**Issue by anthraxx** [tj/terminal-table#70]
Hey, first: thanks for your work :smile: 

I would like to kindly ask for a new release... quote some time has passed and there are several projects that stick with the 1.4.5 version because of https://github.com/tj/terminal-table/issues/59.
It would be really awesome if we can get a new release after nearly 1 year :smile_cat:

**Comment by nateberkopec** [comment]
Done! Pushed as 1.6.0.

**Comment by anthraxx** [comment]
merci
