### ISSUE TITLE
Syntax Error terminal-table/table.rb:252

### ISSUE THREAD

**Issue by khirod12** [tj/terminal-table#79]
terminal-table/table.rb:252: syntax error, unexpected tLPAREN_ARG
      resolve = -> (colspan, full_width, index = 0) do

Ruby Version : 1.9.3 
terminal-table version : 1.7.2

Thanks,
Khirod

**Comment by nateberkopec** [comment]
Sorry about that. We don't have automated CI, so I haven't been testing against older Ruby versions. This is a legacy gem so I'm sure it has lots of users on legacy Ruby versions as well, so I would like to try to keep 1.9x+ support if we can. For now you can stick with 1.7.1.

**Comment by nateberkopec** [comment]
Fixed in 1.7.3.
