### ISSUE TITLE
No License File 

### ISSUE THREAD

**Issue by Jonjoe** [tj/terminal-table#84]
The repository should ideally contain a licence file. The file should be called "LICENSE.md". I would recommend using the MIT license https://opensource.org/licenses/MIT. I would submit a PR but rights to the plugin should be set by the owner. 

Here is a nice guide on licensing in GitHub :). 
https://help.github.com/articles/licensing-a-repository/

**Comment by nateberkopec** [comment]
Sure. I'm not the copyright holder of this repository, so @tj can you tell us exactly which license you're comfortable with for `terminal-table`?

**Comment by leoarnold** [comment]
Have you noticed the MIT license statement at the bottom of README.rdoc?

**Comment by nateberkopec** [comment]
LOL I have not. We should put it into a separate LICENSE.MD file to follow convention, though.
