### ISSUE TITLE
:colspan creates conflicts with colorize

### ISSUE THREAD

**Issue by FluffyCode** [tj/terminal-table#95]
(Say that title ten times fast...)

Using terminal-table has been fantastic for me, particularly due to its compatibility with colorize. I even combine colors with :border_x, :border_y and :border_i to create custom-colored tables/borders.

However I got around to experimenting with :colspan to split the display of "cell" data, and colorize ends up breaking :border_y.

![table_sc](https://user-images.githubusercontent.com/1455644/32801649-84db77a2-c932-11e7-9cea-edbc8f0c6b60.png)

The tables turn out as such:

![table_result](https://user-images.githubusercontent.com/1455644/32801597-65864486-c932-11e7-94db-ee781e76285f.png)

Of course, I can remove the :border_y styling to fix it...

![table_result2](https://user-images.githubusercontent.com/1455644/32801767-dfef3020-c932-11e7-9f9d-a73307db2f5e.png)

...but then I don't have my schnazzy blue dividers.

Capy-pasta-able code, in case you'd like to experiment:

> require 'colorize'
> require 'terminal-table'

> original_sample_data = [
> ["Sep 2016", 33, [-38, -53.52], 46, [-25, -35.21]],
> ["Oct 2016", 35, [2, 6.06], 50, [4, 8.69]]
> ]

> table = Terminal::Table.new headings: ["Month".cyan,"Monthly IT".cyan,"IT Difference OPM".cyan,
>   "Monthly OOT".cyan,"OOT Difference OPM".cyan], rows: original_sample_data

> table.style = { padding_left: 2, padding_right: 2, border_x: "-".blue, border_y: "|".blue, border_i: "+".blue }

> puts table

> puts ""
> puts "^ good table"
> puts "v wonky talbe"
> puts ""

> split_column_sample_data = [
> ["Sep 2016", 33, -38, -53.52, 46, -25, -35.21],
> ["Oct 2016", 35, 2, 6.06, 50, 4, 8.69]
> ]

> table = Terminal::Table.new headings: ["Month".cyan,"Monthly IT".cyan,
>   {value: "IT Difference OPM".cyan, colspan: 2}, "Monthly OOT".cyan,
>   {value: "OOT Difference OPM".cyan, colspan: 2}], rows: split_column_sample_data

> table.style = { padding_left: 2, padding_right: 2, border_x: "-".blue, border_y: "|".blue, border_i: "+".blue }

> puts table

**Comment by nanobowers** [comment]
@nateberkopec  I think this can be closed -   bug fixed as part of #113
